"""Update relationships

Revision ID: 0b68b08a9aaf
Revises: 2bb68d8df13e
Create Date: 2024-02-01 09:37:03.934273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b68b08a9aaf'
down_revision = '2bb68d8df13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_course_description_key', 'course', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_course_description_key', 'course', ['course_description'])
    # ### end Alembic commands ###
