"""Add course_link_image to Course

Revision ID: 5fbcf5523af1
Revises: 19ef9e0b722f
Create Date: 2024-01-29 19:20:21.277199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbcf5523af1'
down_revision = '19ef9e0b722f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_image', sa.LargeBinary(), nullable=True))
    op.drop_column('course', 'course_link_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_link_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('course', 'course_image')
    # ### end Alembic commands ###
