"""Initial Database

Revision ID: 6ad50fc8c3f8
Revises: 
Create Date: 2024-01-31 20:03:29.585210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad50fc8c3f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('programming_language',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_name')
    )
    op.create_table('provider',
    sa.Column('provider_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_description', sa.String(length=255), nullable=True),
    sa.Column('course_rate', sa.Integer(), nullable=True),
    sa.Column('course_path', sa.String(length=255), nullable=False),
    sa.Column('course_image', sa.LargeBinary(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_description'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('course_path')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('course_programming_language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['programming_language.language_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_programming_language')
    op.drop_table('skill')
    op.drop_table('course')
    op.drop_table('provider')
    op.drop_table('programming_language')
    op.drop_table('category')
    # ### end Alembic commands ###
